language: node_js
node_js:
  - 'lts/*'
cache:
  directories:
    - "node_modules"
deploy:
  skip_cleanup: true
  provider: script
  script: bash Tools/travis_deploy.sh
  on:
    all_branches: true
    condition: $TRAVIS_EVENT_TYPE  =~ ^api|cron$
